services:
  - type: web
    name: sme-analytica-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT smeanalytica.api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
